ERROR:root:name 'True5' is not defined
Traceback (most recent call last):
  File "C:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 963, in <module>
    global_manager.set('DEBUG_remove_fog_of_war', True5) #False by default
NameError: name 'True5' is not defined
