ERROR:root:<class 'Exception'>
Traceback (most recent call last):
  File "c:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 35, in <module>
    main_loop.main_loop(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 193, in main_loop
    main_loop_tools.update_display(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop_tools.py", line 130, in update_display
    current_button.draw()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\dice.py", line 187, in draw
    self.roll()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\dice.py", line 154, in roll
    self.global_manager.get('current_dice_rolling_notification').remove()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\action_notifications.py", line 104, in remove
    super().remove()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\notifications.py", line 91, in remove
    notification_manager.notification_to_front(notification_manager.notification_queue[0])
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\data_managers.py", line 653, in notification_to_front
    new_notification = action_notifications.advertising_campaign_notification(scaling.scale_coordinates(self.notification_x, self.notification_y, self.global_manager), scaling.scale_width(self.notification_width,
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\action_notifications.py", line 548, in __init__
    global_manager.get('sound_manager').queue_sound('voices/advertising/commodities/' + global_manager.get('current_advertised_commodity'), channel)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\data_managers.py", line 756, in queue_sound
    current_sound = pygame.mixer.Sound('sounds/' + file_name + '.wav')
FileNotFoundError: No file 'sounds/voices/advertising/commodities/exotic wood.wav' found in working directory 'C:\Users\vikto\Documents\Old computer files\SFA'.
