ERROR:root:vehicle.can_move() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "C:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 1050, in <module>
    main_loop.main_loop(global_manager)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 173, in main_loop
    current_button.on_click()
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\actor_display_tools\buttons.py", line 2902, in on_click
    attached_mob.follow_automatic_route()
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\pmobs.py", line 150, in follow_automatic_route
    while self.can_follow_automatic_route():
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\pmobs.py", line 144, in can_follow_automatic_route
    return(self.can_move(x_change, y_change, False))
TypeError: vehicle.can_move() takes 3 positional arguments but 4 were given
