ERROR:root:local variable 'second_result' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 998, in <module>
    main_loop.main_loop(global_manager)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 43, in main_loop
    current_button.on_click()
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\actor_display_tools\buttons.py", line 1395, in on_click
    current_mob.track_beasts()
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\battalions.py", line 422, in track_beasts
    print(second_result)
UnboundLocalError: local variable 'second_result' referenced before assignment
