ERROR:root:No file 'graphics/misc/empty_damaged.png' found in working directory 'C:\Users\vikto\Documents\Old computer files\SFA'.
Traceback (most recent call last):
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\images.py", line 640, in set_image
    self.image = pygame.image.load('graphics/' + self.image_id)
FileNotFoundError: No file 'graphics/misc/empty_damaged.png' found in working directory 'C:\Users\vikto\Documents\Old computer files\SFA'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 1045, in <module>
    main_loop.main_loop(global_manager)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 43, in main_loop
    current_button.on_click()
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\buttons.py", line 896, in on_click
    self.global_manager.get('save_load_manager').load_game('save1.pickle')
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\save_load_tools.py", line 356, in load_game
    self.global_manager.get('actor_creation_manager').create(True, current_actor_dict, self.global_manager)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\actor_creation_tools.py", line 111, in create
    new_actor = buildings.warehouses(from_save, input_dict, global_manager)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\buildings.py", line 486, in __init__
    super().__init__(from_save, input_dict, global_manager)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\buildings.py", line 65, in __init__
    self.set_damaged(True, True)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\buildings.py", line 182, in set_damaged
    self.set_image('default')
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\actors.py", line 125, in set_image
    current_image.set_image(new_image)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\images.py", line 643, in set_image
    self.image = pygame.image.load('graphics/' + self.image_id)
FileNotFoundError: No file 'graphics/misc/empty_damaged.png' found in working directory 'C:\Users\vikto\Documents\Old computer files\SFA'.
