ERROR:root:<class 'Exception'>
Traceback (most recent call last):
  File "c:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 36, in <module>
    main_loop.main_loop(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 165, in main_loop
    current_button.on_click()#prioritize clicking buttons that appear above other buttons and don't press the ones
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\notifications.py", line 72, in on_click
    self.remove()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\action_notifications.py", line 800, in remove
    self.global_manager.get('artifact_search_result')[0].complete_artifact_search()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\group_types\expeditions.py", line 675, in complete_artifact_search
    if location == self.global_manager.get('current_lore_mission').artifact_location:
AttributeError: 'str' object has no attribute 'artifact_location'
